### ISSUE TITLE
타입 추가 의견

### ISSUE THREAD

**Issue by eunjeongsong** [mohwa/emnida#2]
문자열이 JSON 포맷을 가지는 문자열인지를 판별해주는 함수를 추가하는 것에 대해 생각해봤습니다.
아래 코드 처럼 문자열을 전달 받고, 그 문자가 JSON형태인지를 판별하여 parsing 해야하는 경험이 있었습니다.

```javascript
function IsJsonString(str) {
  try {
    const json = JSON.parse(str);
    return (typeof json === 'object');
  } catch (e) {
    return false;
  }
}
```

현재 repo에 추가될 수 있는 타입인지 확신이 들지는 않지만 🤔 
요렇게 쓰는 경우가 종종 있을 것 같아 의견 남겨봅니다.
추가 의견 부탁드립니다! 🙏

**Comment by mohwa** [comment]
@eunjeongsong 님,

> 문자열이 JSON 포맷을 가지는 문자열인지를 판별해주는 함수를 추가하는 것에 대해 생각해봤습니다.
아래 코드 처럼 문자열을 전달 받고, 그 문자가 JSON형태인지를 판별하여 parsing 해야하는 경험이 있었습니다.

좋은 의견 같습니다. 생각해보니, 저도 비슷한 경험이 있었던것 같습니다.

**Comment by mohwa** [comment]
@eunjeongsong,

관련 PR 이 추가되었습니다. 확인 부탁드립니다.

https://github.com/mohwa/emnida/pull/4

**Comment by mohwa** [comment]
이 작업(https://github.com/mohwa/emnida/commit/2ea036d1d2eacd2205e2c6c1b4b7fa2dc15009c9)을 통해, 관련 내용이 반영되었습니다.
